image: registry.app.ipl/docker/images/dind:python37

variables:
  DOCKER_HOST: tcp://127.0.0.1:2375

services:
  - alias: ololo
    name: docker:18.09.7-dind
    command: ["--insecure-registry=registry.app.ipl"]

stages:
  - venv
  - test
  - build

venv:
  stage: venv
  script:
    - env
    - make venv
  artifacts:
    paths:
      - .venv/
    expire_in: 1 day
  tags:
    - kube-test

flake8:
  stage: test
  script:
    - make flake8
  dependencies:
    - venv
  tags:
    - kube-test

bandit:
  stage: test
  script:
    - make bandit
  dependencies:
    - venv
  tags:
    - kube-test

mypy:
  stage: test
  script:
    - make mypy
  dependencies:
    - venv
  tags:
    - kube-test

safety:
  stage: test
  script:
    - make safety
  dependencies:
    - venv
  tags:
    - kube-test

black:
  stage: test
  script:
    - make black
  dependencies:
    - venv
  tags:
    - kube-test

test:
  stage: test
  artifacts:
    paths:
      - coverage
    expire_in: 1 day
  before_script:
    - chmod +x /usr/local/bin/docker-compose # TODO: fix it dind:python37
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make test
  coverage: /\d+\%\s*$/
  dependencies:
    - venv
  tags:
    - kube-test

build:
  stage: build
  script:
    - sed -i -E 's/^(__version__\s*=\s*)['"'"'"].*?+['"'"'"](.*)$/\1'"'"${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"'"'\2/' ipapp/__init__.py
    - sed -i -E 's/^(__build_stamp__\s*=\s*)[0-9]+$/\1'`date +%s`'/' ipapp/__init__.py
    - make build
    - mkdir -p /pip/ipapp/
    - .venv/bin/twine upload -u __token__ -p $PYPI_TOKEN dist/*
    - cp dist/* /pip/ipapp/
  dependencies:
    - venv
  artifacts:
    paths:
      - .venv/
    expire_in: 1 day
  tags:
    - build
  only:
    - tags
    - master

pages:
  stage: build
  script:
    - make docs
    - mkdir -p public
    - cp -R docs/build/html/* public/
  dependencies:
    - venv
  artifacts:
    paths:
      - public
    expire_in: 1 day
  tags:
    - build
#  only:
#    - tags
