image: registry.app.ipl/docker/images/dind-python37:master

variables:
  DOCKER_HOST: tcp://127.0.0.1:2375

services:
  - alias: ololo
    name: docker:18.09.7-dind
    command: ["--insecure-registry=registry.app.ipl"]

stages:
  - venv
  - test
  - build

venv:
  stage: venv
  script:
    - env
    - make venv
  artifacts:
    paths:
      - .venv/
    expire_in: 1 day
  tags:
    - kube-test

.linter:
  stage: test
  dependencies:
    - venv
  tags:
    - kube-test

flake8:
  extends: .linter
  script:
    - make flake8

bandit:
  extends: .linter
  script:
    - make bandit

mypy:
  extends: .linter
  script:
    - make mypy

safety:
  extends: .linter
  script:
    - make safety

black:
  extends: .linter
  script:
    - make black

test:
  extends: .linter
  artifacts:
    paths:
      - coverage
    expire_in: 1 day
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make test
  coverage: /\d+\%\s*$/

build:
  stage: build
  script:
    - sed -i -E 's/^(__version__\s*=\s*)['"'"'"].*?+['"'"'"](.*)$/\1'"'"${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"'"'\2/' ipapp/__init__.py
    - sed -i -E 's/^(__build_stamp__\s*=\s*)[0-9]+$/\1'`date +%s`'/' ipapp/__init__.py
    - poetry version "${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - make build
    - poetry publish -u __token__ -p "$PYPI_TOKEN" -v
    - poetry config repositories.inplat https://pip.sys.ipl/simple/
    - poetry publish -r inplat -u pypi_ipapp -p "$PYPI_TOKEN_IPL" -v
  dependencies:
    - venv
  artifacts:
    paths:
      - .venv/
    expire_in: 1 day
  tags:
    - build
  only:
    - tags

build-master:
  stage: build
  script:
    - sed -i -E 's/^(__version__\s*=\s*)['"'"'"].*?+['"'"'"](.*)$/\1'"'"${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"'"'\2/' ipapp/__init__.py
    - sed -i -E 's/^(__build_stamp__\s*=\s*)[0-9]+$/\1'`date +%s`'/' ipapp/__init__.py
    - make build
    - poetry config repositories.inplat https://pip.sys.ipl/simple/
    - poetry publish -r inplat -u pypi_ipapp -p "$PYPI_TOKEN_IPL" -v
  dependencies:
    - venv
  artifacts:
    paths:
      - .venv/
    expire_in: 1 day
  tags:
    - build
  only:
    - master
    - merge_requests

pages:
  stage: build
  script:
    - make docs
    - mkdir -p public
    - cp -R docs/build/html/* public/
  dependencies:
    - venv
  artifacts:
    paths:
      - public
    expire_in: 1 day
  tags:
    - build
#  only:
#    - tags
