image: registry.app.ipl/docker/images/dind:python37

variables:
  DOCKER_HOST: tcp://127.0.0.1:2375

services:
- alias: ololo
  name: docker:18.09.7-dind

stages:
  - venv
  - lint
  - test

venv:
  stage: venv
  script:
    - env
    - make venv
  artifacts:
    paths:
    - .venv/
  tags:
    - kube-test

flake8:
  stage: lint
  script:
    - make flake8
  dependencies:
    - venv
  tags:
    - kube-test

bandit:
  stage: lint
  script:
    - make bandit
  dependencies:
    - venv
  tags:
    - kube-test

mypy:
  stage: lint
  script:
    - make mypy
  dependencies:
    - venv
  tags:
    - kube-test

safety:
  stage: lint
  script:
    - make safety
  dependencies:
    - venv
  tags:
    - kube-test

black:
  stage: lint
  script:
    - make black
  dependencies:
    - venv
  tags:
    - kube-test

build:
  stage: test
  artifacts:
    paths:
      - coverage
  script:
    - make test
  coverage: /\d+\%\s*$/
  dependencies:
    - venv
  tags:
    - kube-test
